---
#
# Ansible managed
#
repository:
  description: Install and configure BareOS File Daemon on your system.
  homepage: https://robertdebock.nl/
  topics: bareos, infrastructure, linux, storage, system, tools, ansible, molecule, tox, playbook
