---

- name: encryption | Install python3-cryptography
  ansible.builtin.package:
    name: "{{ bareos_fd_encryption_packages }}"

- name: encryption | Generate private key
  community.crypto.openssl_privatekey:
    path: /etc/bareos/{{ bareos_fd_hostname }}-private.key
    owner: bareos
    group: bareos
    mode: "0600"

- name: encryption | Generate csr for public key
  community.crypto.openssl_csr:
    path: /etc/bareos/{{ bareos_fd_hostname }}-public.csr
    privatekey_path: /etc/bareos/{{ bareos_fd_hostname }}-private.key
    common_name: "{{ bareos_fd_hostname }}"
    owner: bareos
    group: bareos
    mode: "0644"

- name: encryption | Generate public key
  community.crypto.x509_certificate:
    path: /etc/bareos/{{ bareos_fd_hostname }}-public.key
    privatekey_path: /etc/bareos/{{ bareos_fd_hostname }}-private.key
    csr_path: /etc/bareos/{{ bareos_fd_hostname }}-public.csr
    provider: selfsigned
    owner: bareos
    group: bareos
    mode: "0644"

- name: encryption | Read private key
  ansible.builtin.slurp:
    src: /etc/bareos/{{ bareos_fd_hostname }}-private.key
  register: bareos_fd_encryption_private_key

- name: encryption | Read public key
  ansible.builtin.slurp:
    src: /etc/bareos/{{ bareos_fd_hostname }}-public.key
  register: bareos_fd_encryption_public_key

- name: encryption | Combine private and public key
  ansible.builtin.copy:
    content: "{{ bareos_fd_encryption_private_key.content | b64decode }}{{ bareos_fd_encryption_public_key.content | b64decode }}"
    dest: /etc/bareos/{{ bareos_fd_hostname }}.pem
    owner: bareos
    group: bareos
    mode: "0600"
  notify:
    - Check configuration
    - Restart bareos-filedaemon

- name: encryption | Place master public key
  ansible.builtin.copy:
    content: "{{ bareos_fd_encryption_master_public_key }}"
    dest: /etc/bareos/master.pub.key
    owner: bareos
    group: bareos
    mode: "0640"
  notify:
    - Check configuration
    - Restart bareos-filedaemon
