---

argument_specs:
  main:
    short_description: "Install and configure BareOS Director on your system."
    description: >
      Install and configure BareOS Director on your system.
    author: Adfinis
    options:
      bareos_dir_backup_configurations:
        type: "bool"
        default: false
        description: "Backup the configuration files."
      bareos_dir_hostname:
        type: "str"
        default: "{{ inventory_hostname }}"
        description: "The hostname of the Director."
      bareos_dir_password:
        type: "str"
        default: "secretpassword"
        description: "The password for the Director."
      bareos_dir_queryfile:
        type: "str"
        default: "/usr/lib/bareos/scripts/query.sql"
        description: "The query file."
      bareos_dir_max_concurrent_jobs:
        type: "int"
        default: 10
        description: "The maximum number of concurrent jobs."
      bareos_dir_message:
        type: "str"
        default: "Daemon"
        description: "The messages configuration to use."
      bareos_dir_tls_enable:
        type: "bool"
        default: true
        description: >
          Enable TLS support.
          If no certificates are configured PSK (Pre Shared Keys) ciphers will be used.
          If the other side does not support TLS, or cleartext is configured the connection will be aborted.
      bareos_dir_tls_verify_peer:
        type: "bool"
        default: false
        description: >
          Request and verify the peers certificate.
          In server context, unless the TLS Allowed CN configuration directive is specified,
          any client certificate signed by a known-CA will be accepted.
          In client context, the server certificate CommonName attribute is checked against the
          Address and TLS Allowed CN configuration directives.
      bareos_dir_tls_ca_cert_src:
        type: "str"
        description: "The CA Certificate for the Director (src)"
      bareos_dir_tls_ca_cert_dest:
        type: "str"
        description: "The CA Certificate for the Director (dest)"
      bareos_dir_tls_cert_src:
        type: "str"
        description: "The TLS certificate of the director (src)"
      bareos_dir_tls_cert_dest:
        type: "str"
        description: "The TLS certificate of the director (dest)"
      bareos_dir_tls_cert_key_src:
        type: "str"
        description: "The TLS certificate key of the director (src)"
      bareos_dir_tls_cert_key_dest:
        type: "str"
        description: "The TLS certificate key of the director (dest)"
      bareos_dir_tls_allowed_cns:
        type: "list"
        required: false
        description: >
          CN attribute of allowed peer certificates.
          If `bareos_dir_tls_verify_peer` is true,
          all connection request certificates will be checked against this list.
      bareos_dir_catalogs:
        type: "list"
        default: []
        description: "A list of catalogs to configure."
      bareos_dir_consoles:
        type: "list"
        default: []
        description: "A list of consoles to configure."
        elements: "dict"
        options:
          name:
            type: "str"
            required: true
            description: >
              The name of the console.
              This name must match the name specified at the Console client.
          description:
            type: "str"
          password:
            type: "str"
            required: true
            description: >
              Specifies the password that must be supplied for a named Bareos Console to be authorized.
          commandacl:
            type: "list"
            elements: "str"
          jobacl:
            type: "list"
            elements: "str"
          profile:
            type: "str"
            description: >
              See https://docs.bareos.org/Configuration/Director.html#directorresourceprofile
          tls_enable:
            type: "bool"
            default: true
            description: "Enable TLS support."
          use_pam_authentication:
            type: "bool"
            default: false
            description: >
              Use PAM authentication for this console.
              Cannot be used in combination with the option `profile` or `commandacl`!
              See: https://github.com/bareos/bareos/tree/master/contrib/misc/bareos_pam_integration#pam-configuration

      bareos_dir_counters:
        type: "list"
        default: []
        description: "A list of counters to configure."
      bareos_dir_clients:
        type: "list"
        default: []
        description: "A list of clients to configure."
      bareos_dir_filesets:
        type: "list"
        default: []
        description: "A list of filesets to configure."
      bareos_dir_jobdefs:
        type: "list"
        default: []
        description: "A list of jobdefs to configure."
      bareos_dir_jobs:
        type: "list"
        default: []
        description: "A list of jobs to configure."
      bareos_dir_messages:
        type: "list"
        default: []
        description: "A list of messages to configure."
      bareos_dir_pools:
        type: "list"
        default: []
        description: "A list of pools to configure."
      bareos_dir_profiles:
        type: "list"
        default: []
        description: "A list of profiles to configure."
      bareos_dir_schedules:
        type: "list"
        default: []
        description: "A list of schedules to configure."
      bareos_dir_storages:
        type: "list"
        default: []
        description: "A list of storages to configure."
      bareos_dir_install_debug_packages:
        type: "bool"
        default: false
        description: "Install debug packages. This requires the debug repositories to be enabled."
      bareos_dir_plugins:
        type: "list"
        description: "A list of Bareos Director plugins"
        elements: "str"
        required: false
        version_added: v1.1.0
      bareos_dir_pam_auth_enable:
        type: "bool"
        default: false
        description: >
          Setup Bareos Director to use PAM authentication via Unix socket or LDAP socket.
          Follows the setup guide at
          https://github.com/bareos/bareos/tree/master/contrib/misc/bareos_pam_integration#pam-configuration
      bareos_dir_pam_auth_method:
        type: "str"
        default: "unix"
        choices:
          - "ldap"
          - "unix"
          - "sss"
        description: "Decide if Unix, SSS or LDAP socket should be used for PAM authentication"
      bareos_dir_pam_auth_profile:
        type: "str"
        default: "webui-admin"
        description: "The Bareos profile to use for the user, after a successful login attempt"
      bareos_dir_pam_auth_username:
        type: "str"
        default: "pam-adduser"
        description: >-
          Technical user account for the Bareos Console connection.
          Required to be able to add the user resources in Bareos, after a successful PAM authentication.
      bareos_dir_pam_auth_password:
        type: "str"
        default: "lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname')"
        description: >-
          Password for technical user account for the Bareos Console connection.
          Randomized, but idempotent password will be generated if variable is unset.
      bareos_dir_pam_auth_tls_enable:
        type: "bool"
        default: false
        description: >-
          If TLS should be used for the Bareos Console
          WebUI does not support pre-shared keys (PSK), so if this is desired,
          an actual CA and certificates need to be in place.
      bareos_dir_overwrite_dir_conf:
        type: "bool"
        default: true
        description: >-
          This variable is used to control the behavior of applying the bareos-dir.conf template
          in /etc/bareos/bareos-dir.d/director/bareos-dir.conf everytime.
          The bareos_dir role is also intended to deploy the client (Filedaemon) configurations on
          the Director. If multiple separate repositories are used then this variable can be set to false,
          so not all repositories overwrite the "global" Director configuration.
      bareos_dir_heartbeat_interval:
        type: "int"
        default: 0
        description: >-
          Configure a keepalive interval (heartbeat) on the sockets used by the Bareos Director in seconds.
          0 disables it.
