---
# handlers file for bareos_fd

- name: Check configuration
  ansible.builtin.command: "/usr/sbin/bareos-fd --test-config"
  changed_when: no

- name: Restart bareos-filedaemon
  ansible.builtin.service:
    name: "{{ bareos_fd_service }}"
    state: restarted
