---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: ansible-role-bareos_fd
      bareos_fd_backup_configurations: yes
      bareos_fd_directors:
        - name: "bareos-dir"
          password: "secretpassword"
          monitor: no
          connection_from_client_to_director: yes
          connection_from_director_to_client: no
          tls_enable: yes
          tls_verify_peer: no
        - name: "disabled-director"
          enabled: no
      bareos_fd_messages:
        - name: "Standard"
          director:
            server: bareos-dir
            messages:
              - all
              - "!skipped"
              - "!restored"
          description: "Send relevant messages to the Director."
          append:
            file: "/var/log/bareos/bareos.log"
            messages:
              - all
              - "!skipped"
              - "!terminate"
          console:
            - all
            - "!skipped"
            - "!saved"
        - name: "disabled-message"
          enabled: no
