---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Install psycopg dependency community.postgresql
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

  tasks:
    - name: Check if port 9101 is listening
      ansible.builtin.wait_for:
        port: 9101

    - name: Test configuration
      ansible.builtin.command:
        cmd: bareos-dir --test-config
      become_user: bareos
      register: bareos_dir_test_config
      failed_when:
        - bareos_dir_test_config.stdout_lines is search("There are configuration warnings")

    - name: Test bconsole
      ansible.builtin.command:
        cmd: bconsole --test-config
      register: bareos_dir_test_config
      failed_when:
        - bareos_dir_test_config.stdout_lines is search("There are configuration warnings") or
          bareos_dir_test_config.stdout_lines is search("CONFIG ERROR")

    - name: Check if bareos python-dir plugin is installed
      ansible.builtin.package:
        name:
          - bareos-director-python-plugin
        state: present
      check_mode: true
      diff: true
      register: _result
      failed_when: _result.changed

    - name: Verify PSQL access to Catalog database
      community.postgresql.postgresql_info:
        db: bareos
        login_user: bareos
        filter: version
      become: true
      become_user: bareos
      register: _psql_result
      failed_when:
        - '"postgresql" not in _psql_result.version.raw | lower'
