---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if port 9102 is listening
      ansible.builtin.wait_for:
        port: 9102

    - name: Test configuration
      ansible.builtin.command:
        cmd: bareos-fd --test-config
