---

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '3 2 2 * *'

jobs:
  test:
    uses: adfinis/github-workflows-bareos/.github/workflows/molecule.yaml@eedff15b52be3c117bd5f7a28492494596399311 # v0.8.0
    with:
      distros: |
        [
          "debian13",
          "debian12",
          "debian11",
          "fedora42",
          "ubuntu2404",
          "ubuntu2204"
        ]
