---

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '3 2 2 * *'

jobs:
  test:
    uses: adfinis/github-workflows-bareos/.github/workflows/molecule.yaml@179afeef02c828ee39b355f2b157cd5505d600b8
    with:
      systems: |
        {
          "config": [
            {
              "image": "debian",
              "tag": "latest"
            },
            {
              "image": "debian",
              "tag": "bullseye"
            },
            {
              "image": "enterpriselinux",
              "tag": "latest"
            },
            {
              "image": "fedora",
              "tag": "40"
            },
            {
              "image": "fedora",
              "tag": "latest"
            },
            {
              "image": "ubuntu",
              "tag": "jammy"
            },
            {
              "image": "ubuntu",
              "tag": "latest"
            }
          ]
        }
