---

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '3 2 2 * *'

jobs:
  test:
    uses: adfinis/github-workflows-bareos/.github/workflows/molecule.yaml@7b2184d76870cc7c281d081a6ebabc15264dcc1f # v0.10.0
    with:
      distros: |
        [
          "debian13",
          "debian12",
          "fedora43",
          "fedora44",
          "ubuntu2604",
          "ubuntu2404",
          "ubuntu2204"
        ]
